---
- name: Update apt cache
  become: true
  apt:
      update_cache: yes
      cache_valid_time: 3600

- name: Ensure standard packages are installed
  become: true
  apt:
      name: "{{ item }}"
      state: present
  with_items: "{{ web_pentest_packages }}"

# Postman Install

- name: Check for postman
  command: which postman
  register: postman_path
  failed_when: postman_path.rc >= 2

- name: download postman
  get_url: 
      url: https://dl.pstmn.io/download/latest/linux64
      dest: /tmp/postman.tar.gz
      mode: 0775
  when: postman_path.rc == 1

- name: unzip postman
  become: true
  command: tar -zxf /tmp/postman.tar.gz -C /opt
  when: postman_path.rc == 1

- name: symlink postman
  file:
      src: /opt/Postman/Postman
      dest: /usr/bin/postman
      state: link
  when: postman_path.rc == 1

# Burp community install
- name: check for burp
  command: which burp
  register: burp_path
  failed_when: burp_path.rc >=2

- name: create burp directory
  become: true
  file:
      path: /opt/burp
      owner: root
      group: pentesters
      mode: 0775
      state: directory
  when: burp_path.rc == 1

- name: download burp community
  become: true
  get_url:
      url: https://portswigger.net/burp/releases/download?product=community&version=1.7.33&type=jar
      dest: /opt/burp/burp_community.jar
      owner: root
      group: pentesters
      mode: 0775
  when: burp_path.rc == 1

- name: add burp start script
  become: true
  copy:
      src: burp.sh
      dest: /usr/bin/burp
      mode: 0755
  when: burp_path.rc == 1
